Algoritmo "par_ou_impar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2025
Var
 N: Inteiro


Inicio
 Escreva ("Digite um número qualquer: ")
 leia(N)
 
 Se (N % 2 = 0) entao
  Escreval("O número ", N, "é PAR. ")
 Senao
  Escreval("O número ", N, "é Ímpar. ")
 fimse


Fimalgoritmo