Algoritmo "Voto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2025
Var

N1: inteiro

Inicio
 Escreva("Digite sua idade ")
 leia(N1)
 Se (N1 >= 16) entao
 Escreval ("Sua idade é permitida votar! ")
 Senao
 Escreval ("Sua idade NÃO é permitida votar")
 FimSe


Fimalgoritmo