Algoritmo "idade"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2025
Var
 ano_atual, ano_nascimento, idade: Inteiro


Inicio
 Escreva ("Em que ano nos estamos? ")
 Leia (ano_atual)
 
 Escreva ("Em que ano eu nasci? ")
 Leia (ano_nascimento)
 
 idade <- ano_atual - ano_nascimento
 
 Escreval ("A minha idade e", idade)


Fimalgoritmo